name: talapas-calculator #Environment name
dependencies:
  - python=3.6
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-bootstrap-components
    - dash-html-components
    - plotly
    - gunicorn # for app deployment
